using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Utilities
{
    public record ATAChapterElement
    {
        public string ChapNmbr;
        public string Description;
        public string Area;

        public ATAChapterElement(
            string chapNmbr
            , string description
            , string area)
        {
            ChapNmbr = chapNmbr;
            Description = description;
            Area = area;
        }
    }
    public record ATAChapSubElement
    {
        public string ChapNmbr;
        public string ChapDesc;
        public string SubNmbr;
        public string SubDesc;

        public ATAChapSubElement(
            string chapNmbr
            , string chapDesc
            , string subNmbr
            , string subDesc)
        {
            ChapNmbr = chapNmbr;
            ChapDesc = chapDesc;
            SubNmbr = subNmbr;
            SubDesc = subDesc;
        }
    }

    public static class ATAReference
    {
        public static List<ATAChapterElement> ATAChapterList = new List<ATAChapterElement>()
        {
            new ATAChapterElement("01", "Reserved For Airline Use", "Miscellaneous"),
            new ATAChapterElement("02", "Reserved For Airline Use", "Miscellaneous"),
            new ATAChapterElement("03", "Reserved For Airline Use", "Miscellaneous"),
            new ATAChapterElement("04", "Reserved For Airline Use", "Miscellaneous"),
            new ATAChapterElement("05", "Time Limits/Maintenance Checks", "Miscellaneous"),
            new ATAChapterElement("06", "Dimensions And Areas", "Miscellaneous"),
            new ATAChapterElement("07", "Lifting And Shoring", "Miscellaneous"),
            new ATAChapterElement("08", "Leveling And Weighing.", "Miscellaneous"),
            new ATAChapterElement("09", "Towing And Taxi", "Miscellaneous"),
            new ATAChapterElement("10", "Parking, Mooring, Storage And Return To Service", "Miscellaneous"),
            new ATAChapterElement("11", "Placards And Markings", "Miscellaneous"),
            new ATAChapterElement("12", "Servicing - Routine Maintenance", "Miscellaneous"),
            new ATAChapterElement("18", "Vibration And Noise Analysis (Helicopter Only)", "Miscellaneous"),
            new ATAChapterElement("89", "Flight Test Installation", "Miscellaneous"),
            new ATAChapterElement("20", "Standard Practices - Airframe", "Airframe Systems"),
            new ATAChapterElement("21", "Air Conditioning And Pressurization", "Airframe Systems"),
            new ATAChapterElement("22", "Auto Flight", "Airframe Systems"),
            new ATAChapterElement("23", "Communications", "Airframe Systems"),
            new ATAChapterElement("24", "Electrical Power", "Airframe Systems"),
            new ATAChapterElement("25", "Equipment/Furnishings", "Airframe Systems"),
            new ATAChapterElement("26", "Fire Protection", "Airframe Systems"),
            new ATAChapterElement("27", "Flight Controls", "Airframe Systems"),
            new ATAChapterElement("28", "Fuel", "Airframe Systems"),
            new ATAChapterElement("29", "Hydraulic Power", "Airframe Systems"),
            new ATAChapterElement("30", "Ice And Rain Protection", "Airframe Systems"),
            new ATAChapterElement("31", "Indicating / Recording System", "Airframe Systems"),
            new ATAChapterElement("32", "Landing Gear", "Airframe Systems"),
            new ATAChapterElement("33", "Lights", "Airframe Systems"),
            new ATAChapterElement("34", "Navigation", "Airframe Systems"),
            new ATAChapterElement("35", "Oxygen", "Airframe Systems"),
            new ATAChapterElement("36", "Pneumatic", "Airframe Systems"),
            new ATAChapterElement("37", "Vacuum", "Airframe Systems"),
            new ATAChapterElement("38", "Water/Waste", "Airframe Systems"),
            new ATAChapterElement("39", "Electrical - Electronic Panels And Multipurpose", ""),
            new ATAChapterElement("40", "Multisystem", "Components"),
            new ATAChapterElement("41", "Water Ballast", "Components"),
            new ATAChapterElement("42", "Integrated Modular Avionics", "Components"),
            new ATAChapterElement("44", "Cabin Systems", "Components"),
            new ATAChapterElement("45", "Diagnostic And Maintenance System", "Components"),
            new ATAChapterElement("46", "Information Systems", "Components"),
            new ATAChapterElement("47", "Nitrogen Generation System", "Components"),
            new ATAChapterElement("48", "In Flight Fuel Dispensing", "Components"),
            new ATAChapterElement("49", "Airborne Auxiliary Power", "Components"),
            new ATAChapterElement("50", "Cargo And Accessory Compartments", "Components"),
            new ATAChapterElement("51", "Standard Practices And Structures - General", "Structure"),
            new ATAChapterElement("52", "Doors", "Structure"),
            new ATAChapterElement("53", "Fuselage", "Structure"),
            new ATAChapterElement("54", "Nacelles/Pylons", "Structure"),
            new ATAChapterElement("55", "Stabilizers", "Structure"),
            new ATAChapterElement("56", "Windows", "Structure"),
            new ATAChapterElement("57", "Wings", "Structure"),
            new ATAChapterElement("61", "Propellers", "Power Plant"),
            new ATAChapterElement("70", "Standard Practices Engine", "Power Plant"),
            new ATAChapterElement("71", "Power Plant", "Power Plant"),
            new ATAChapterElement("72", "Engine - Reciprocating", "Power Plant"),
            new ATAChapterElement("73", "Engine - Fuel And Control", "Power Plant"),
            new ATAChapterElement("74", "Ignition", "Power Plant"),
            new ATAChapterElement("75", "Bleed Air", "Power Plant"),
            new ATAChapterElement("76", "Engine Controls", "Power Plant"),
            new ATAChapterElement("77", "Engine Indicating", "Power Plant"),
            new ATAChapterElement("78", "Exhaust", "Power Plant"),
            new ATAChapterElement("79", "Oil", "Power Plant"),
            new ATAChapterElement("80", "Starting", "Power Plant"),
            new ATAChapterElement("81", "Turbines (Reciprocating Engines)", "Power Plant"),
            new ATAChapterElement("82", "Engine Water Injection", "Power Plant"),
            new ATAChapterElement("83", "Accessory Gearboxes", "Power Plant"),
            new ATAChapterElement("84", "Propulsion Augmentation", "Power Plant"),
            new ATAChapterElement("85", "Fuel Cell Systems", "Power Plant"),
            new ATAChapterElement("91", "Charts", "Miscellaneous"),
            new ATAChapterElement("92", "Electrical System Installation", "Miscellaneous")
        };

        public static List<ATAChapSubElement> ATAChapSubList = new List<ATAChapSubElement>()
        {
             new ATAChapSubElement( "05", "Time Limits/ Maintenance Checks", "00", "General"),
             new ATAChapSubElement( "05", "Time Limits/ Maintenance Checks", "10", "Time Limits"),
             new ATAChapSubElement( "05", "Time Limits/ Maintenance Checks", "20", "Scheduled Maintenance Checks"),
             new ATAChapSubElement( "05", "Time Limits/ Maintenance Checks", "30", "Reserved"),
             new ATAChapSubElement( "05", "Time Limits/ Maintenance Checks", "40", "Reserved"),
             new ATAChapSubElement( "05", "Time Limits/ Maintenance Checks", "50", "Unscheduled Maintenance checks"),
             new ATAChapSubElement( "07", "Lifting & Shoring", "00", "General"),
             new ATAChapSubElement( "07", "Lifting & Shoring", "10", "Jacking"),
             new ATAChapSubElement( "07", "Lifting & Shoring", "20", "Shoring"),
             new ATAChapSubElement( "08", "Leveling & Weighing", "00", "General"),
             new ATAChapSubElement( "08", "Leveling & Weighing", "10", "Weighing and Balancing"),
             new ATAChapSubElement( "08", "Leveling & Weighing", "20", "Leveling"),
             new ATAChapSubElement( "09", "Towing & Taxiing", "00", "General"),
             new ATAChapSubElement( "09", "Towing & Taxiing", "10", "Towing"),
             new ATAChapSubElement( "09", "Towing & Taxiing", "20", "Taxiing"),
             new ATAChapSubElement( "11", "Placards And Markings", "00", "General"),
             new ATAChapSubElement( "11", "Placards And Markings", "10", "Exterior Color Schemes and Markings"),
             new ATAChapSubElement( "11", "Placards And Markings", "20", "Exterior Placards and Markings"),
             new ATAChapSubElement( "11", "Placards And Markings", "30", "Interior Placards"),
             new ATAChapSubElement( "12", "Servicing", "00", "General"),
             new ATAChapSubElement( "12", "Servicing", "10", "Replenishing"),
             new ATAChapSubElement( "12", "Servicing", "20", "Scheduled Servicing"),
             new ATAChapSubElement( "12", "Servicing", "30", "Unscheduled Servicing"),
             new ATAChapSubElement( "18", "Vibration And Noise Analysis (Helicopter Only)", "00", "GENERAL -"),
             new ATAChapSubElement( "18", "Vibration And Noise Analysis (Helicopter Only)", "10", "VIBRATION ANALYSIS"),
             new ATAChapSubElement( "18", "Vibration And Noise Analysis (Helicopter Only)", "20", "NOISE ANALYSIS"),
             new ATAChapSubElement( "20", "Standard Practices", "90", "*Reserved for Airline Use"),
             new ATAChapSubElement( "22", "Auto Flight", "00", "General"),
             new ATAChapSubElement( "22", "Auto Flight", "10", "Autopilot"),
             new ATAChapSubElement( "22", "Auto Flight", "20", "Speed-Attitude Correction"),
             new ATAChapSubElement( "22", "Auto Flight", "30", "Auto Throttle"),
             new ATAChapSubElement( "22", "Auto Flight", "40", "System Monitor"),
             new ATAChapSubElement( "22", "Auto Flight", "50", "Aerodynamic Load Alleviating"),
             new ATAChapSubElement( "23", "Communications", "00", "General"),
             new ATAChapSubElement( "23", "Communications", "10", "Speech Communications"),
             new ATAChapSubElement( "23", "Communications", "15", "SATCOM"),
             new ATAChapSubElement( "23", "Communications", "20", "Data Transmission and Automatic Calling"),
             new ATAChapSubElement( "23", "Communications", "30", "Comfort"),
             new ATAChapSubElement( "23", "Communications", "40", "Interphone"),
             new ATAChapSubElement( "23", "Communications", "50", "Audio Integrating"),
             new ATAChapSubElement( "23", "Communications", "60", "Static Discharging"),
             new ATAChapSubElement( "23", "Communications", "70", "Audio & Video Monitoring"),
             new ATAChapSubElement( "23", "Communications", "80", "Integrated Automatic"),
             new ATAChapSubElement( "24", "Electrical Power", "00", "General"),
             new ATAChapSubElement( "24", "Electrical Power", "10", "Generator Drive"),
             new ATAChapSubElement( "24", "Electrical Power", "20", "AC Generation"),
             new ATAChapSubElement( "24", "Electrical Power", "30", "DC Generation"),
             new ATAChapSubElement( "24", "Electrical Power", "40", "External Power"),
             new ATAChapSubElement( "24", "Electrical Power", "50", "AC Electrical Load Distribution"),
             new ATAChapSubElement( "24", "Electrical Power", "60", "DC Electrical Load Distribution"),
             new ATAChapSubElement( "25", "Equipment/Furnishings", "00", "General"),
             new ATAChapSubElement( "25", "Equipment/Furnishings", "10", "Flight Compartment"),
             new ATAChapSubElement( "25", "Equipment/Furnishings", "20", "Passenger Compartment"),
             new ATAChapSubElement( "25", "Equipment/Furnishings", "30", "Galley"),
             new ATAChapSubElement( "25", "Equipment/Furnishings", "40", "Lavatories"),
             new ATAChapSubElement( "25", "Equipment/Furnishings", "50", "Additional Compartments"),
             new ATAChapSubElement( "25", "Equipment/Furnishings", "60", "Emergency"),
             new ATAChapSubElement( "25", "Equipment/Furnishings", "70", "Available"),
             new ATAChapSubElement( "25", "Equipment/Furnishings", "80", "Insulation"),
             new ATAChapSubElement( "26", "Fire Protection", "00", "General"),
             new ATAChapSubElement( "26", "Fire Protection", "10", "Detection"),
             new ATAChapSubElement( "26", "Fire Protection", "20", "Extinguishing"),
             new ATAChapSubElement( "26", "Fire Protection", "30", "Explosion Suppression"),
             new ATAChapSubElement( "27", "Flight Controls", "00", "General"),
             new ATAChapSubElement( "27", "Flight Controls", "10", "Aileron & Tab"),
             new ATAChapSubElement( "27", "Flight Controls", "20", "Rudder & Tab"),
             new ATAChapSubElement( "27", "Flight Controls", "30", "Elevator & Tab"),
             new ATAChapSubElement( "27", "Flight Controls", "40", "Horizontal Stabilizer"),
             new ATAChapSubElement( "27", "Flight Controls", "50", "Flaps"),
             new ATAChapSubElement( "27", "Flight Controls", "60", "Spoiler, Drag Devices and Variable Aerodynamic Fairings"),
             new ATAChapSubElement( "27", "Flight Controls", "70", "Gust Lock & Dampener"),
             new ATAChapSubElement( "27", "Flight Controls", "80", "Lift Augmenting"),
             new ATAChapSubElement( "28", "Fuel", "00", "General"),
             new ATAChapSubElement( "28", "Fuel", "10", "Storage"),
             new ATAChapSubElement( "28", "Fuel", "20", "Distribution"),
             new ATAChapSubElement( "28", "Fuel", "30", "Dump"),
             new ATAChapSubElement( "28", "Fuel", "40", "Indicating"),
             new ATAChapSubElement( "29", "Hydraulic Power", "00", "General"),
             new ATAChapSubElement( "29", "Hydraulic Power", "10", "Main"),
             new ATAChapSubElement( "29", "Hydraulic Power", "20", "Auxiliary"),
             new ATAChapSubElement( "29", "Hydraulic Power", "30", "Indicating"),
             new ATAChapSubElement( "30", "Ice And Rain Protection", "00", "General"),
             new ATAChapSubElement( "30", "Ice And Rain Protection", "10", "Airfoil"),
             new ATAChapSubElement( "30", "Ice And Rain Protection", "20", "Air Intakes"),
             new ATAChapSubElement( "30", "Ice And Rain Protection", "30", "Pitot and Static"),
             new ATAChapSubElement( "30", "Ice And Rain Protection", "40", "Windows, Windshields and Doors"),
             new ATAChapSubElement( "30", "Ice And Rain Protection", "50", "Antennas and Radomes"),
             new ATAChapSubElement( "30", "Ice And Rain Protection", "60", "Propellers/Rotors"),
             new ATAChapSubElement( "30", "Ice And Rain Protection", "70", "Water Lines"),
             new ATAChapSubElement( "30", "Ice And Rain Protection", "80", "Detection"),
             new ATAChapSubElement( "31", "Indicating/Recording Systems", "00", "General"),
             new ATAChapSubElement( "31", "Indicating/Recording Systems", "10", "Instrument & Control Panels"),
             new ATAChapSubElement( "31", "Indicating/Recording Systems", "20", "Independent Instruments"),
             new ATAChapSubElement( "31", "Indicating/Recording Systems", "30", "Recorders"),
             new ATAChapSubElement( "31", "Indicating/Recording Systems", "40", "Central Computers"),
             new ATAChapSubElement( "31", "Indicating/Recording Systems", "50", "Central Warning Systems"),
             new ATAChapSubElement( "31", "Indicating/Recording Systems", "60", "Central Display Systems"),
             new ATAChapSubElement( "31", "Indicating/Recording Systems", "70", "Automatic Data Reporting Systems"),
             new ATAChapSubElement( "32", "Landing Gear", "00", "General"),
             new ATAChapSubElement( "32", "Landing Gear", "10", "Main Gear and Doors"),
             new ATAChapSubElement( "32", "Landing Gear", "20", "Nose Gear and Doors"),
             new ATAChapSubElement( "32", "Landing Gear", "30", "Extension and Retraction"),
             new ATAChapSubElement( "32", "Landing Gear", "40", "Wheels and Brakes"),
             new ATAChapSubElement( "32", "Landing Gear", "50", "Steering"),
             new ATAChapSubElement( "32", "Landing Gear", "60", "Position and Warning"),
             new ATAChapSubElement( "32", "Landing Gear", "70", "Supplementary Gear"),
             new ATAChapSubElement( "33", "Lights", "00", "General"),
             new ATAChapSubElement( "33", "Lights", "10", "Flight Compartment"),
             new ATAChapSubElement( "33", "Lights", "20", "Passenger Compartment"),
             new ATAChapSubElement( "33", "Lights", "30", "Cargo and Service Compartments"),
             new ATAChapSubElement( "33", "Lights", "40", "Exterior"),
             new ATAChapSubElement( "33", "Lights", "50", "Emergency Lighting"),
             new ATAChapSubElement( "34", "Navigation", "00", "General"),
             new ATAChapSubElement( "34", "Navigation", "10", "Flight Environment"),
             new ATAChapSubElement( "34", "Navigation", "20", "Attitude & Direction"),
             new ATAChapSubElement( "34", "Navigation", "30", "Landing and Taxiing Aids"),
             new ATAChapSubElement( "34", "Navigation", "40", "Independent Position Determining"),
             new ATAChapSubElement( "34", "Navigation", "50", "Dependent Position Determining"),
             new ATAChapSubElement( "34", "Navigation", "60", "Flight Management Computing"),
             new ATAChapSubElement( "35", "Oxygen", "00", "General"),
             new ATAChapSubElement( "35", "Oxygen", "10", "Crew"),
             new ATAChapSubElement( "35", "Oxygen", "20", "Passenger"),
             new ATAChapSubElement( "35", "Oxygen", "30", "Portable"),
             new ATAChapSubElement( "36", "Pneumatic", "00", "General"),
             new ATAChapSubElement( "36", "Pneumatic", "10", "Distribution"),
             new ATAChapSubElement( "36", "Pneumatic", "20", "Indicating"),
             new ATAChapSubElement( "37", "Vacuum", "00", "General"),
             new ATAChapSubElement( "37", "Vacuum", "10", "Distribution"),
             new ATAChapSubElement( "37", "Vacuum", "20", "Indicating"),
             new ATAChapSubElement( "38", "Water/Waste", "00", "General"),
             new ATAChapSubElement( "38", "Water/Waste", "10", "Potable"),
             new ATAChapSubElement( "38", "Water/Waste", "20", "Wash"),
             new ATAChapSubElement( "38", "Water/Waste", "30", "Waste Disposal"),
             new ATAChapSubElement( "38", "Water/Waste", "40", "Air Supply"),
             new ATAChapSubElement( "41", "Water Ballast", "00", "General"),
             new ATAChapSubElement( "41", "Water Ballast", "10", "Storage"),
             new ATAChapSubElement( "41", "Water Ballast", "20", "Dump"),
             new ATAChapSubElement( "41", "Water Ballast", "30", "Indication"),
             new ATAChapSubElement( "44", "Cabin Systems", "00", "General"),
             new ATAChapSubElement( "44", "Cabin Systems", "10", "Cabin Core System"),
             new ATAChapSubElement( "44", "Cabin Systems", "20", "Inflight Entertainment System"),
             new ATAChapSubElement( "44", "Cabin Systems", "30", "External Communication System"),
             new ATAChapSubElement( "44", "Cabin Systems", "40", "Cabin Mass Memory System"),
             new ATAChapSubElement( "44", "Cabin Systems", "50", "Cabin Monitoring System"),
             new ATAChapSubElement( "44", "Cabin Systems", "60", "Miscellaneous Cabin System"),
             new ATAChapSubElement( "45", "Central Maintenance System", "00", "General"),
             new ATAChapSubElement( "45", "Central Maintenance System", "05", "thru -19 CMS/Aircraft General"),
             new ATAChapSubElement( "45", "Central Maintenance System", "20", "thru -49 CMS/Airframe Systems"),
             new ATAChapSubElement( "45", "Central Maintenance System", "45", "Central Maintenance System"),
             new ATAChapSubElement( "45", "Central Maintenance System", "50", "thru -59 CMS/Structures"),
             new ATAChapSubElement( "45", "Central Maintenance System", "60", "thru -69 CMS/Propellers"),
             new ATAChapSubElement( "45", "Central Maintenance System", "70", "thru -89 CMS/Power Plant"),
             new ATAChapSubElement( "46", "Information Systems", "00", "General"),
             new ATAChapSubElement( "46", "Information Systems", "10", "Airplane General Information Systems"),
             new ATAChapSubElement( "46", "Information Systems", "20", "Flight Deck Information Systems"),
             new ATAChapSubElement( "46", "Information Systems", "30", "Maintenance Information Systems"),
             new ATAChapSubElement( "46", "Information Systems", "40", "Passenger Cabin Information Systems"),
             new ATAChapSubElement( "46", "Information Systems", "50", "Miscellaneous Information Systems"),
             new ATAChapSubElement( "49", "Airborne Auxiliary Power", "00", "General"),
             new ATAChapSubElement( "49", "Airborne Auxiliary Power", "10", "Power Plant"),
             new ATAChapSubElement( "49", "Airborne Auxiliary Power", "20", "Engine"),
             new ATAChapSubElement( "49", "Airborne Auxiliary Power", "30", "Engine Fuel and Control"),
             new ATAChapSubElement( "49", "Airborne Auxiliary Power", "40", "Ignition/Starting"),
             new ATAChapSubElement( "49", "Airborne Auxiliary Power", "50", "Air"),
             new ATAChapSubElement( "49", "Airborne Auxiliary Power", "60", "Engine Controls ."),
             new ATAChapSubElement( "49", "Airborne Auxiliary Power", "70", "Indicating"),
             new ATAChapSubElement( "49", "Airborne Auxiliary Power", "80", "Exhaust"),
             new ATAChapSubElement( "49", "Airborne Auxiliary Power", "90", "Oil"),
             new ATAChapSubElement( "50", "Cargo And Accessory Compartments", "00", "General"),
             new ATAChapSubElement( "50", "Cargo And Accessory Compartments", "10", "Cargo Compartments"),
             new ATAChapSubElement( "50", "Cargo And Accessory Compartments", "20", "Cargo Loading Systems"),
             new ATAChapSubElement( "50", "Cargo And Accessory Compartments", "30", "Cargo Related Systems"),
             new ATAChapSubElement( "50", "Cargo And Accessory Compartments", "40", "Available"),
             new ATAChapSubElement( "50", "Cargo And Accessory Compartments", "50", "Accessory"),
             new ATAChapSubElement( "50", "Cargo And Accessory Compartments", "60", "Insulation"),
             new ATAChapSubElement( "51", "Standard Practices, General", "00", "General"),
             new ATAChapSubElement( "51", "Standard Practices, General", "10", "Investigation, Cleanup and Aerodynamic Smoothness"),
             new ATAChapSubElement( "51", "Standard Practices, General", "20", "Processes"),
             new ATAChapSubElement( "51", "Standard Practices, General", "30", "Materials"),
             new ATAChapSubElement( "51", "Standard Practices, General", "40", "Fasteners"),
             new ATAChapSubElement( "51", "Standard Practices, General", "50", "Support of Airplane for Repair and Alignment Check Procedures"),
             new ATAChapSubElement( "51", "Standard Practices, General", "60", "Control-Surface Balancing"),
             new ATAChapSubElement( "51", "Standard Practices, General", "70", "Repairs"),
             new ATAChapSubElement( "51", "Standard Practices, General", "80", "Electrical Bonding"),
             new ATAChapSubElement( "52", "Doors", "00", "General"),
             new ATAChapSubElement( "52", "Doors", "10", "Passenger/Crew"),
             new ATAChapSubElement( "52", "Doors", "20", "Emergency Exit"),
             new ATAChapSubElement( "52", "Doors", "30", "Cargo"),
             new ATAChapSubElement( "52", "Doors", "40", "Service and Miscellaneous"),
             new ATAChapSubElement( "52", "Doors", "50", "Fixed Interior"),
             new ATAChapSubElement( "52", "Doors", "60", "Entrance Stairs"),
             new ATAChapSubElement( "52", "Doors", "70", "Monitoring and Operation"),
             new ATAChapSubElement( "52", "Doors", "80", "Landing Gear"),
             new ATAChapSubElement( "53", "Fuselage", "00", "General"),
             new ATAChapSubElement( "53", "Fuselage", "10", "thru -90 (As Required) Fuselage Sections"),
             new ATAChapSubElement( "54", "Nacelles/Pylons", "00", "General"),
             new ATAChapSubElement( "54", "Nacelles/Pylons", "10", "thru -40 (As Required) Nacelle Section"),
             new ATAChapSubElement( "54", "Nacelles/Pylons", "50", "thru -80 (As Required) Pylon"),
             new ATAChapSubElement( "55", "Stabilizers", "00", "General"),
             new ATAChapSubElement( "55", "Stabilizers", "10", "Horizontal Stabilizer or Canard"),
             new ATAChapSubElement( "55", "Stabilizers", "20", "Elevator"),
             new ATAChapSubElement( "55", "Stabilizers", "30", "Vertical Stabilizer"),
             new ATAChapSubElement( "55", "Stabilizers", "40", "Rudder"),
             new ATAChapSubElement( "56", "Windows", "00", "General"),
             new ATAChapSubElement( "56", "Windows", "10", "Flight Compartment"),
             new ATAChapSubElement( "56", "Windows", "20", "Passenger Compartment"),
             new ATAChapSubElement( "56", "Windows", "30", "Door"),
             new ATAChapSubElement( "56", "Windows", "40", "Inspection and Observation"),
             new ATAChapSubElement( "57", "Wings", "00", "General"),
             new ATAChapSubElement( "57", "Wings", "10", "Center Wing"),
             new ATAChapSubElement( "57", "Wings", "20", "Outer Wing"),
             new ATAChapSubElement( "57", "Wings", "30", "Wing Tip"),
             new ATAChapSubElement( "57", "Wings", "40", "Leading Edge and Leading Edge Devices"),
             new ATAChapSubElement( "57", "Wings", "50", "Trailing Edge Trailing Edge Devices"),
             new ATAChapSubElement( "57", "Wings", "60", "Ailerons and Elevons"),
             new ATAChapSubElement( "57", "Wings", "70", "Spoilers"),
             new ATAChapSubElement( "57", "Wings", "80", "(as required)"),
             new ATAChapSubElement( "57", "Wings", "90", "Wing Folding System"),
             new ATAChapSubElement( "61", "Propellers/Propulsion", "00", "General"),
             new ATAChapSubElement( "61", "Propellers/Propulsion", "10", "Propeller Assembly"),
             new ATAChapSubElement( "61", "Propellers/Propulsion", "20", "Controlling"),
             new ATAChapSubElement( "61", "Propellers/Propulsion", "30", "Braking"),
             new ATAChapSubElement( "61", "Propellers/Propulsion", "40", "Indicating"),
             new ATAChapSubElement( "61", "Propellers/Propulsion", "50", "Propulsor Duct"),
             new ATAChapSubElement( "62", "Rotor(S)", "00", "General"),
             new ATAChapSubElement( "62", "Rotor(S)", "10", "Rotor blades"),
             new ATAChapSubElement( "62", "Rotor(S)", "20", "Rotor head(s)"),
             new ATAChapSubElement( "62", "Rotor(S)", "30", "Rotor Shaft(s)/Swashplate Assy(ies)"),
             new ATAChapSubElement( "62", "Rotor(S)", "40", ""),
             new ATAChapSubElement( "63", "Rotor Drive(S)", "00", "General"),
             new ATAChapSubElement( "63", "Rotor Drive(S)", "10", "Engine/Gearbox couplings"),
             new ATAChapSubElement( "63", "Rotor Drive(S)", "20", "Gearbox(es)"),
             new ATAChapSubElement( "63", "Rotor Drive(S)", "30", "Mounts, attachments"),
             new ATAChapSubElement( "63", "Rotor Drive(S)", "40", "Indicating"),
             new ATAChapSubElement( "64", "Tail Rotor", "00", "General"),
             new ATAChapSubElement( "64", "20*", "30", "Available"),
             new ATAChapSubElement( "64", "20*", "40", "Indicating"),
             new ATAChapSubElement( "65", "Tail Rotor Drive", "00", "General"),
             new ATAChapSubElement( "65", "Tail Rotor Drive", "10", "Shafts"),
             new ATAChapSubElement( "65", "Tail Rotor Drive", "20", "Gearboxes"),
             new ATAChapSubElement( "65", "Tail Rotor Drive", "30", "Available"),
             new ATAChapSubElement( "65", "Tail Rotor Drive", "40", "Indicating"),
             new ATAChapSubElement( "66", "Folding Blades/Pylon", "00", "General"),
             new ATAChapSubElement( "66", "Folding Blades/Pylon", "10", "Rotor blades"),
             new ATAChapSubElement( "66", "Folding Blades/Pylon", "20", "Tail pylon"),
             new ATAChapSubElement( "66", "Folding Blades/Pylon", "30", "Controls and Indicating"),
             new ATAChapSubElement( "67", "Rotors Flight Control", "00", "General"),
             new ATAChapSubElement( "67", "Rotors Flight Control", "10", "Rotor"),
             new ATAChapSubElement( "67", "Rotors Flight Control", "20", "Anti-torque Rotor control (Yaw control)"),
             new ATAChapSubElement( "67", "Rotors Flight Control", "30", "Servo-control System"),
             new ATAChapSubElement( "71", "Power Plant", "00", "General"),
             new ATAChapSubElement( "71", "Power Plant", "10", "Cowling"),
             new ATAChapSubElement( "71", "Power Plant", "30", "Fireseals"),
             new ATAChapSubElement( "71", "Power Plant", "40", "Attach Fittings"),
             new ATAChapSubElement( "71", "Power Plant", "50", "Electrical Harness"),
             new ATAChapSubElement( "71", "Power Plant", "60", "Air Intakes"),
             new ATAChapSubElement( "71", "Power Plant", "70", "Engine Drains"),
             new ATAChapSubElement( "72", "Engine Turbine/Turbo Prop Ducted Fan/Unducted Fan", "00", "General"),
             new ATAChapSubElement( "72", "Engine Turbine/Turbo Prop Ducted Fan/Unducted Fan", "10", "Reduction Gear, Shaft Section (Turbo-Prop and/or Front Mounted Gear Driven Propulsor)"),
             new ATAChapSubElement( "72", "Engine Turbine/Turbo Prop Ducted Fan/Unducted Fan", "20", "Air Inlet Section"),
             new ATAChapSubElement( "72", "Engine Turbine/Turbo Prop Ducted Fan/Unducted Fan", "30", "Compressor Section"),
             new ATAChapSubElement( "72", "Engine Turbine/Turbo Prop Ducted Fan/Unducted Fan", "40", "Combustion Section"),
             new ATAChapSubElement( "72", "Engine Turbine/Turbo Prop Ducted Fan/Unducted Fan", "50", "Turbine Section"),
             new ATAChapSubElement( "72", "Engine Turbine/Turbo Prop Ducted Fan/Unducted Fan", "60", "Accessory Drives"),
             new ATAChapSubElement( "72", "Engine Turbine/Turbo Prop Ducted Fan/Unducted Fan", "70", "By-pass Section"),
             new ATAChapSubElement( "72", "Engine Turbine/Turbo Prop Ducted Fan/Unducted Fan", "80", "Propulsor Section (Rear Mounted)"),
             new ATAChapSubElement( "73", "Engine Fuel And Control", "00", "General"),
             new ATAChapSubElement( "73", "Engine Fuel And Control", "10", "Distribution"),
             new ATAChapSubElement( "73", "Engine Fuel And Control", "20", "Controlling"),
             new ATAChapSubElement( "73", "Engine Fuel And Control", "30", "Indicating"),
             new ATAChapSubElement( "74", "Ignition", "00", "General"),
             new ATAChapSubElement( "74", "Ignition", "10", "Electrical Power"),
             new ATAChapSubElement( "74", "Ignition", "20", "Distribution"),
             new ATAChapSubElement( "74", "Ignition", "30", "Switching"),
             new ATAChapSubElement( "75", "Air", "00", "General"),
             new ATAChapSubElement( "75", "Air", "10", "Engine Anti-Icing"),
             new ATAChapSubElement( "75", "Air", "20", "Cooling"),
             new ATAChapSubElement( "75", "Air", "30", "Compressor Control"),
             new ATAChapSubElement( "75", "Air", "40", "Indicating"),
             new ATAChapSubElement( "76", "Engine Controls", "00", "General"),
             new ATAChapSubElement( "76", "Engine Controls", "10", "Power Control"),
             new ATAChapSubElement( "76", "Engine Controls", "20", "Emergency Shutdown"),
             new ATAChapSubElement( "77", "Engine Indicating", "00", "General"),
             new ATAChapSubElement( "77", "Engine Indicating", "10", "Power"),
             new ATAChapSubElement( "77", "Engine Indicating", "20", "Temperature"),
             new ATAChapSubElement( "77", "Engine Indicating", "30", "Analyzers That"),
             new ATAChapSubElement( "77", "Engine Indicating", "40", "Integrated Engine Instrument Systems"),
             new ATAChapSubElement( "78", "Exhaust", "00", "General"),
             new ATAChapSubElement( "78", "Exhaust", "10", "Collector/Nozzle"),
             new ATAChapSubElement( "78", "Exhaust", "20", "Noise Suppressor"),
             new ATAChapSubElement( "78", "Exhaust", "30", "Thrust Reverser"),
             new ATAChapSubElement( "78", "Exhaust", "40", "Supplementary Air"),
             new ATAChapSubElement( "79", "Oil", "00", "General"),
             new ATAChapSubElement( "79", "Oil", "10", "Storage"),
             new ATAChapSubElement( "79", "Oil", "20", "Distribution"),
             new ATAChapSubElement( "79", "Oil", "30", "Indicating"),
             new ATAChapSubElement( "80", "Starting", "00", "General"),
             new ATAChapSubElement( "80", "Starting", "10", "Cranking"),
             new ATAChapSubElement( "81", "Turbines", "00", "General"),
             new ATAChapSubElement( "81", "Turbines", "10", "Power Recovery"),
             new ATAChapSubElement( "81", "Turbines", "20", "Turbo-Supercharger"),
             new ATAChapSubElement( "82", "Water Injection", "00", "General"),
             new ATAChapSubElement( "82", "Water Injection", "10", "Storage"),
             new ATAChapSubElement( "82", "Water Injection", "20", "Distribution"),
             new ATAChapSubElement( "82", "Water Injection", "30", "Dumping and Purging"),
             new ATAChapSubElement( "82", "Water Injection", "40", "Indicating"),
             new ATAChapSubElement( "83", "Accessory Gear", "00", "General"),
             new ATAChapSubElement( "83", "Accessory Gear", "10", "Drive Shaft Section"),
             new ATAChapSubElement( "83", "Accessory Gear", "20", "Gearbox Section"),
             new ATAChapSubElement( "84", "Propulsion Augmentation", "00", "General"),
             new ATAChapSubElement( "84", "Propulsion Augmentation", "10", "Jet Assist Takeoff"),
             new ATAChapSubElement( "85", "Reciprocating Engine", "00", "General"),
             new ATAChapSubElement( "85", "Reciprocating Engine", "10", "Fuel Cell Stack"),
             new ATAChapSubElement( "97", "General", "00-00", "Zone 100 Fuselage Lower"),
             new ATAChapSubElement( "97", "General", "00-00", "Zone 200 Fuselage Top"),
             new ATAChapSubElement( "97", "General", "00-00", "Zone 300 Stabilizers"),
             new ATAChapSubElement( "97", "General", "00-00", "Zone 400 Nacelles-Pylons"),
             new ATAChapSubElement( "97", "General", "00-00", "Zone 500 Left Wing"),
             new ATAChapSubElement( "97", "General", "00-00", "Zone 600 Right Wing"),
             new ATAChapSubElement( "97", "General", "00-00", "Zone 700 Landing Gear Compartment"),
             new ATAChapSubElement( "97", "General", "00-00", "Zone 800 Doors"),
             new ATAChapSubElement( "97", "General", "00-00", "Zone 900 Lavatories & Galleys"),
             new ATAChapSubElement( "97", "General", "20-00", "Electrical Standard Items/Practices"),
             new ATAChapSubElement( "97", "General", "21-00", "Air Conditioning - General"),
             new ATAChapSubElement( "97", "General", "21-10", "Compression"),
             new ATAChapSubElement( "97", "General", "21-20", "Distribution"),
             new ATAChapSubElement( "97", "General", "21-30", "Pressurization Control"),
             new ATAChapSubElement( "97", "General", "21-40", "Heating"),
             new ATAChapSubElement( "97", "General", "21-50", "Cooling"),
             new ATAChapSubElement( "97", "General", "21-60", "Temperature Control"),
             new ATAChapSubElement( "97", "General", "21-70", "Moisture/Air Contaminant Control"),
             new ATAChapSubElement( "97", "General", "22-00", "Auto Flight - General"),
             new ATAChapSubElement( "97", "General", "22-10", "Autopilot"),
             new ATAChapSubElement( "97", "General", "22-20", "Speed - Attitude Correction"),
             new ATAChapSubElement( "97", "General", "22-30", "Auto Throttle"),
             new ATAChapSubElement( "97", "General", "22-40", "System Monitors"),
             new ATAChapSubElement( "97", "General", "22-50", "Aerodynamic Load Alleviating"),
             new ATAChapSubElement( "97", "General", "23-00", "Communications - General"),
             new ATAChapSubElement( "97", "General", "23-10", "Speech Communications"),
             new ATAChapSubElement( "97", "General", "23-15", "SATCOM"),
             new ATAChapSubElement( "97", "General", "23-20", "Data Transmission and Automatic Calling"),
             new ATAChapSubElement( "97", "General", "23-30", "Passenger Address, Entertainment and Comfort"),
             new ATAChapSubElement( "97", "General", "23-40", "Interphone"),
             new ATAChapSubElement( "97", "General", "23-50", "Audio Integrating"),
             new ATAChapSubElement( "97", "General", "23-60", "Static Discharging"),
             new ATAChapSubElement( "97", "General", "23-70", "Audio and Video Monitoring"),
             new ATAChapSubElement( "97", "General", "23-80", "Integrated Automatic Tuning"),
             new ATAChapSubElement( "97", "General", "24-00", "Electrical Power - General"),
             new ATAChapSubElement( "97", "General", "24-10", "Generator Drive"),
             new ATAChapSubElement( "97", "General", "24-20", "AC Generation"),
             new ATAChapSubElement( "97", "General", "24-30", "DC Generation"),
             new ATAChapSubElement( "97", "General", "24-40", "External Power"),
             new ATAChapSubElement( "97", "General", "24-50", "AC Electrical Load Distribution"),
             new ATAChapSubElement( "97", "General", "24-60", "DC Electrical Load Distribution"),
             new ATAChapSubElement( "97", "General", "25-00", "Equipment/Furnishings - General"),
             new ATAChapSubElement( "97", "General", "25-10", "Flight Compartment"),
             new ATAChapSubElement( "97", "General", "25-20", "Passenger Compartment"),
             new ATAChapSubElement( "97", "General", "25-30", "Galley"),
             new ATAChapSubElement( "97", "General", "25-40", "Lavatories"),
             new ATAChapSubElement( "97", "General", "25-60", "Emergency"),
             new ATAChapSubElement( "97", "General", "25-80", "Insulation"),
             new ATAChapSubElement( "97", "General", "26-00", "Fire Protection - General"),
             new ATAChapSubElement( "97", "General", "26-10", "Detection"),
             new ATAChapSubElement( "97", "General", "26-20", "Extinguishing"),
             new ATAChapSubElement( "97", "General", "26-30", "Explosion Suppression"),
             new ATAChapSubElement( "97", "General", "27-00", "Flight Controls - General"),
             new ATAChapSubElement( "97", "General", "27-10", "Aileron & Tab"),
             new ATAChapSubElement( "97", "General", "27-20", "Rudder & Tab"),
             new ATAChapSubElement( "97", "General", "27-30", "Elevator & Tab"),
             new ATAChapSubElement( "97", "General", "27-40", "Horizontal Stabilizer"),
             new ATAChapSubElement( "97", "General", "27-50", "Flaps"),
             new ATAChapSubElement( "97", "General", "27-60", "Spoiler, Drag Devices and Variable Aerodynamic Fairings"),
             new ATAChapSubElement( "97", "General", "27-70", "Gust Lock & Dampener"),
             new ATAChapSubElement( "97", "General", "27-80", "Lift Augmenting"),
             new ATAChapSubElement( "97", "General", "28-00", "Fuel - General"),
             new ATAChapSubElement( "97", "General", "28-10", "Storage"),
             new ATAChapSubElement( "97", "General", "28-20", "Distribution"),
             new ATAChapSubElement( "97", "General", "28-30", "Dump"),
             new ATAChapSubElement( "97", "General", "28-40", "Indicating"),
             new ATAChapSubElement( "97", "General", "29-00", "Hydraulic Power - General"),
             new ATAChapSubElement( "97", "General", "29-10", "Main"),
             new ATAChapSubElement( "97", "General", "29-20", "Auxiliary"),
             new ATAChapSubElement( "97", "General", "29-30", "Indicating"),
             new ATAChapSubElement( "97", "General", "30-00", "Ice and Rain Protection - General"),
             new ATAChapSubElement( "97", "General", "30-10", "Airfoil"),
             new ATAChapSubElement( "97", "General", "30-20", "Air Intakes"),
             new ATAChapSubElement( "97", "General", "30-30", "Pitot and Static"),
             new ATAChapSubElement( "97", "General", "30-40", "Windows, Windshields and Doors"),
             new ATAChapSubElement( "97", "General", "30-50", "Antennas And Radomes"),
             new ATAChapSubElement( "97", "General", "30-60", "Propellers/Rotors"),
             new ATAChapSubElement( "97", "General", "30-70", "Water Lines"),
             new ATAChapSubElement( "97", "General", "30-80", "Detection"),
             new ATAChapSubElement( "97", "General", "31-00", "Indicating/Recording Systems - General"),
             new ATAChapSubElement( "97", "General", "31-10", "Instrument and Control Panels"),
             new ATAChapSubElement( "97", "General", "31-20", "Independent Instruments"),
             new ATAChapSubElement( "97", "General", "31-30", "Recorders"),
             new ATAChapSubElement( "97", "General", "31-40", "Central Computers"),
             new ATAChapSubElement( "97", "General", "31-50", "Central Warning Systems"),
             new ATAChapSubElement( "97", "General", "31-60", "Central Display Systems"),
             new ATAChapSubElement( "97", "General", "31-70", "Automatic Data Reporting Systems"),
             new ATAChapSubElement( "97", "General", "32-00", "Landing Gear- General"),
             new ATAChapSubElement( "97", "General", "32-10", "Main Gear and Doors"),
             new ATAChapSubElement( "97", "General", "32-20", "Nose Gear and Doors"),
             new ATAChapSubElement( "97", "General", "32-30", "Extension and Retraction"),
             new ATAChapSubElement( "97", "General", "32-40", "Wheels and Brakes"),
             new ATAChapSubElement( "97", "General", "32-50", "Steering"),
             new ATAChapSubElement( "97", "General", "32-60", "Position And Warning"),
             new ATAChapSubElement( "97", "General", "32-70", "Supplementary Gear"),
             new ATAChapSubElement( "97", "General", "33-00", "Lights - General"),
             new ATAChapSubElement( "97", "General", "33-10", "Flight Compartment"),
             new ATAChapSubElement( "97", "General", "33-20", "Passenger Compartment"),
             new ATAChapSubElement( "97", "General", "33-30", "Cargo and Service Compartments"),
             new ATAChapSubElement( "97", "General", "33-40", "Exterior"),
             new ATAChapSubElement( "97", "General", "33-50", "Emergency Lighting"),
             new ATAChapSubElement( "97", "General", "34-00", "Navigation - General"),
             new ATAChapSubElement( "97", "General", "34-10", "Flight Environment Data"),
             new ATAChapSubElement( "97", "General", "34-20", "Attitude & Direction"),
             new ATAChapSubElement( "97", "General", "34-30", "Landing and Taxiing Aids"),
             new ATAChapSubElement( "97", "General", "34-40", "Independent Position Determining"),
             new ATAChapSubElement( "97", "General", "34-50", "Dependent Position Determining"),
             new ATAChapSubElement( "97", "General", "34-60", "Flight Management Computing"),
             new ATAChapSubElement( "97", "General", "35-00", "Oxygen - General"),
             new ATAChapSubElement( "97", "General", "35-10", "Crew"),
             new ATAChapSubElement( "97", "General", "35-20", "Passenger"),
             new ATAChapSubElement( "97", "General", "35-30", "Portable"),
             new ATAChapSubElement( "97", "General", "36-00", "Pneumatic - General"),
             new ATAChapSubElement( "97", "General", "36-10", "Distribution"),
             new ATAChapSubElement( "97", "General", "36-20", "Indicating"),
             new ATAChapSubElement( "97", "General", "37-00", "Vacuum - General"),
             new ATAChapSubElement( "97", "General", "37-10", "Distribution"),
             new ATAChapSubElement( "97", "General", "37-20", "Indicating"),
             new ATAChapSubElement( "97", "General", "38-00", "Water/Waste - General"),
             new ATAChapSubElement( "97", "General", "38-10", "Potable"),
             new ATAChapSubElement( "97", "General", "38-20", "Wash"),
             new ATAChapSubElement( "97", "General", "38-30", "Waste Disposal"),
             new ATAChapSubElement( "97", "General", "38-40", "Air Supply"),
             new ATAChapSubElement( "97", "General", "44-00", "Cabin Systems - General"),
             new ATAChapSubElement( "97", "General", "44-10", "Cabin Core System"),
             new ATAChapSubElement( "97", "General", "44-20", "In-flight Entertainment System"),
             new ATAChapSubElement( "97", "General", "44-30", "External Communication System"),
             new ATAChapSubElement( "97", "General", "44-40", "Cabin Mass Memory System"),
             new ATAChapSubElement( "97", "General", "44-50", "Cabin Monitoring System"),
             new ATAChapSubElement( "97", "General", "44-60", "Miscellaneous Cabin System"),
             new ATAChapSubElement( "97", "General", "45-00", "Central Maintenance System (CMS) General"),
             new ATAChapSubElement( "97", "General", "45-05", "CMS/Aircraft General"),
             new ATAChapSubElement( "97", "General", "45-20", "CMS/Airframe Systems"),
             new ATAChapSubElement( "97", "General", "45-45", "Central Maintenance System"),
             new ATAChapSubElement( "97", "General", "45-50", "CMS/Structures"),
             new ATAChapSubElement( "97", "General", "45-60", "CMS/Propellers"),
             new ATAChapSubElement( "97", "General", "45-70", "CMS/Power Plant"),
             new ATAChapSubElement( "97", "General", "46-00", "Information Systems - General"),
             new ATAChapSubElement( "97", "General", "46-10", "Airplane General Information Systems"),
             new ATAChapSubElement( "97", "General", "46-20", "Flight Deck Information Systems"),
             new ATAChapSubElement( "97", "General", "46-30", "Maintenance Information Systems"),
             new ATAChapSubElement( "97", "General", "46-40", "Passenger Cabin Information Systems"),
             new ATAChapSubElement( "97", "General", "46-50", "Miscellaneous Information Systems"),
             new ATAChapSubElement( "97", "General", "49-00", "Airborne Auxiliary Power - General"),
             new ATAChapSubElement( "97", "General", "49-10", "Power Plant"),
             new ATAChapSubElement( "97", "General", "49-20", "Engine"),
             new ATAChapSubElement( "97", "General", "49-30", "Engine Fuel And Control"),
             new ATAChapSubElement( "97", "General", "49-40", "Ignition And Starting"),
             new ATAChapSubElement( "97", "General", "49-50", "Air"),
             new ATAChapSubElement( "97", "General", "49-60", "Engine Controls"),
             new ATAChapSubElement( "97", "General", "49-70", "Indicating"),
             new ATAChapSubElement( "97", "General", "49-80", "Exhaust"),
             new ATAChapSubElement( "97", "General", "49-90", "Oil"),
             new ATAChapSubElement( "97", "General", "50-00", "Cargo And Accessory Compartments General"),
             new ATAChapSubElement( "97", "General", "50-10", "Cargo Compartments"),
             new ATAChapSubElement( "97", "General", "50-20", "Cargo Loading Systems"),
             new ATAChapSubElement( "97", "General", "50-30", "Cargo Related Systems"),
             new ATAChapSubElement( "97", "General", "50-40", "Available"),
             new ATAChapSubElement( "97", "General", "50-50", "Accessory Compartments"),
             new ATAChapSubElement( "97", "General", "50-60", "Insulation"),
             new ATAChapSubElement( "97", "General", "52-00", "Doors - General"),
             new ATAChapSubElement( "97", "General", "52-10", "Passenger/Crew"),
             new ATAChapSubElement( "97", "General", "52-20", "Emergency Exit"),
             new ATAChapSubElement( "97", "General", "52-30", "Cargo"),
             new ATAChapSubElement( "97", "General", "52-40", "Service"),
             new ATAChapSubElement( "97", "General", "52-50", "Fixed Interior"),
             new ATAChapSubElement( "97", "General", "52-60", "Entrance Stairs"),
             new ATAChapSubElement( "97", "General", "52-70", "Door Warning"),
             new ATAChapSubElement( "97", "General", "52-80", "Landing Gear"),
             new ATAChapSubElement( "97", "General", "53-00", "Fuselage - General"),
             new ATAChapSubElement( "97", "General", "54-00", "Nacelles/Pylons - General"),
             new ATAChapSubElement( "97", "General", "54-10", "Nacelle Section"),
             new ATAChapSubElement( "97", "General", "54-50", "Pylon"),
             new ATAChapSubElement( "97", "General", "55-00", "Stabilizers - General"),
             new ATAChapSubElement( "97", "General", "55-10", "Horizontal Stabilizer or Canard"),
             new ATAChapSubElement( "97", "General", "55-20", "Elevator"),
             new ATAChapSubElement( "97", "General", "55-30", "Vertical Stabilizer"),
             new ATAChapSubElement( "97", "General", "55-40", "Rudder"),
             new ATAChapSubElement( "97", "General", "56-00", "Windows - General"),
             new ATAChapSubElement( "97", "General", "56-10", "Flight Compartment"),
             new ATAChapSubElement( "97", "General", "56-20", "Passenger Compartment"),
             new ATAChapSubElement( "97", "General", "56-30", "Door"),
             new ATAChapSubElement( "97", "General", "56-40", "Inspection and Observation"),
             new ATAChapSubElement( "97", "General", "57-00", "Wings - General"),
             new ATAChapSubElement( "97", "General", "57-10", "Center Wing"),
             new ATAChapSubElement( "97", "General", "57-20", "Outer Wing"),
             new ATAChapSubElement( "97", "General", "57-30", "Wing Tip"),
             new ATAChapSubElement( "97", "General", "57-40", "Leading Edge and Leading Edge Devices"),
             new ATAChapSubElement( "97", "General", "57-50", "Trailing Edge and Trailing Edge Devices"),
             new ATAChapSubElement( "97", "General", "57-60", "Ailerons"),
             new ATAChapSubElement( "97", "General", "57-70", "Spoilers"),
             new ATAChapSubElement( "97", "General", "57-90", "Wing Folding System"),
             new ATAChapSubElement( "97", "General", "61-00", "Propellers/Propulsors - General"),
             new ATAChapSubElement( "97", "General", "61-10", "Propeller Assembly"),
             new ATAChapSubElement( "97", "General", "61-20", "Controlling"),
             new ATAChapSubElement( "97", "General", "61-30", "Braking"),
             new ATAChapSubElement( "97", "General", "61-40", "Indicating"),
             new ATAChapSubElement( "97", "General", "61-50", "Propulsor Duct"),
             new ATAChapSubElement( "97", "General", "62-00", "Rotors"),
             new ATAChapSubElement( "97", "General", "63-00", "Rotor Drives"),
             new ATAChapSubElement( "97", "General", "64-00", "Tail Rotor"),
             new ATAChapSubElement( "97", "General", "65-00", "Tail Rotor Drive"),
             new ATAChapSubElement( "97", "General", "66-00", "Folding Blades/Pylon"),
             new ATAChapSubElement( "97", "General", "67-00", "Rotors Flight Control"),
             new ATAChapSubElement( "97", "General", "71-00", "Power Plant - General"),
             new ATAChapSubElement( "97", "General", "71-10", "Cowling"),
             new ATAChapSubElement( "97", "General", "71-20", "Mounts"),
             new ATAChapSubElement( "97", "General", "71-30", "Fire seals"),
             new ATAChapSubElement( "97", "General", "71-40", "Attach Fittings"),
             new ATAChapSubElement( "97", "General", "71-50", "Electrical Harness"),
             new ATAChapSubElement( "97", "General", "71-60", "Air Intakes"),
             new ATAChapSubElement( "97", "General", "71-70", "Engine Drains"),
             new ATAChapSubElement( "97", "General", "72-00", "Engine Turbine/Turbo Prop Ducted Fan/Unducted Fan"),
             new ATAChapSubElement( "97", "General", "72-10", "Reduction Gear, Shaft Section (Turbo-Prop and/or Front Mounted Gear Driven Propulsor)"),
             new ATAChapSubElement( "97", "General", "72-20", "Air Inlet Section"),
             new ATAChapSubElement( "97", "General", "72-30", "Compressor Section"),
             new ATAChapSubElement( "97", "General", "72-40", "Combustion Section"),
             new ATAChapSubElement( "97", "General", "72-50", "Turbine Section"),
             new ATAChapSubElement( "97", "General", "72-60", "Accessory Drives"),
             new ATAChapSubElement( "97", "General", "72-70", "By-pass Section"),
             new ATAChapSubElement( "97", "General", "72-80", "Propulsor Section (Rear Mounted)"),
             new ATAChapSubElement( "97", "General", "73-00", "Engine Fuel And Control - General"),
             new ATAChapSubElement( "97", "General", "73-10", "Distribution"),
             new ATAChapSubElement( "97", "General", "73-20", "Controlling"),
             new ATAChapSubElement( "97", "General", "73-30", "Indicating"),
             new ATAChapSubElement( "97", "General", "74-00", "Ignition - General"),
             new ATAChapSubElement( "97", "General", "74-10", "Electrical Power Supply"),
             new ATAChapSubElement( "97", "General", "74-20", "Distribution"),
             new ATAChapSubElement( "97", "General", "74-30", "Switching"),
             new ATAChapSubElement( "97", "General", "75-00", "Air - General"),
             new ATAChapSubElement( "97", "General", "75-10", "Engine Anti-Icing"),
             new ATAChapSubElement( "97", "General", "75-20", "Cooling"),
             new ATAChapSubElement( "97", "General", "75-30", "Compressor Control"),
             new ATAChapSubElement( "97", "General", "75-40", "Indicating"),
             new ATAChapSubElement( "97", "General", "76-00", "Engine Controls - General"),
             new ATAChapSubElement( "97", "General", "76-10", "Power Control"),
             new ATAChapSubElement( "97", "General", "76-20", "Emergency Shutdown"),
             new ATAChapSubElement( "97", "General", "77-00", "Engine Indicating - General"),
             new ATAChapSubElement( "97", "General", "77-10", "Power"),
             new ATAChapSubElement( "97", "General", "77-20", "Temperature"),
             new ATAChapSubElement( "97", "General", "77-30", "Analyzers"),
             new ATAChapSubElement( "97", "General", "77-40", "Integrated Engine Instrument Systems"),
             new ATAChapSubElement( "97", "General", "78-00", "Exhaust - General"),
             new ATAChapSubElement( "97", "General", "78-10", "Collector/Nozzle"),
             new ATAChapSubElement( "97", "General", "78-20", "Noise Suppressor"),
             new ATAChapSubElement( "97", "General", "78-30", "Thrust Reverser"),
             new ATAChapSubElement( "97", "General", "78-40", "Supplementary Air"),
             new ATAChapSubElement( "97", "General", "79-00", "Oil - General"),
             new ATAChapSubElement( "97", "General", "79-10", "Storage"),
             new ATAChapSubElement( "97", "General", "79-30", "Indicating"),
             new ATAChapSubElement( "97", "General", "80-00", "Starting - General"),
             new ATAChapSubElement( "97", "General", "80-10", "Cranking"),

        };
    }
}
